### ISSUE TITLE
Csound submodule is outdated

### ISSUE THREAD

**Issue by ales-tsurko** [neithanmo/csound-rs#10]
There was a new release of Csound. Should it be updated (and so the bindings)?

**Comment by neithanmo** [comment]
Thanks for open this issue.
In regards to the module, Does this update would break something we need to keep minimal compatibility with previous versions...What are the new features the latest Csound comes with??
If they do not represent breaking changes we can add them.

**Comment by ales-tsurko** [comment]
Currently, the module is in the state somewhere between 6.14.0 and 6.15.0. Looks like there were no breaking changes related to the API since then:

https://github.com/csound/csound/releases/tag/6.15.0

There were changes in the WebAudio API, but I think it's not related to the C API.

It would also be more safe to link against a state at a specific release tag (https://github.com/csound/csound/tree/6.15.0) instead of the current state of the `develop` branch.

**Comment by ales-tsurko** [comment]
Do you need help with it? I could provide a PR.

**Comment by neithanmo** [comment]
It would be great if you can implement this.

`It would also be more safe to link against a state at a specific release tag (https://github.com/csound/csound/tree/6.15.0) instead of the current state of the develop branch.`
I agree. So we stick to the latest release tag, without the risk of possible breaking changes or errors

**Comment by ales-tsurko** [comment]
I see you wrote bindings (`csound-sys`) manually. Is there any particular reason for that? Can it be replaced by the bindgen generated bindings?
