### ISSUE TITLE
Moving to bindgen-generated bindings?

### ISSUE THREAD

**Issue by ales-tsurko** [neithanmo/csound-rs#11]
I see you wrote bindings (`csound-sys`) manually. Is there any particular reason for that? Can it be replaced by the bindgen generated bindings?

**Comment by ales-tsurko** [comment]
The only possible issue I see is the enums style. As far as I know, bindgen can't produce enums in the style you did, but we can update the library, so it'll use a new style of enums. Moving to bindgen will allow updating `csound-sys` automatically. The bindings could be generated at build time. Also, bindgen generates documentation and tests.

**Comment by neithanmo** [comment]
That is a good question. So far I do not see problems using it, except that it introduces a new dependency, the one we use with llvm and that is used by Bingen. Currently, this plugin is used by a Gstreamer plugin in Gts-plugins-rs, And I do not like the idea of having to install a llvm component. Please correct me if I am wrong. Let me check if some other plugins there use bindgen under the hood

**Comment by ales-tsurko** [comment]
It's a build only dependency, you don't need it for the end application.

**Comment by neithanmo** [comment]
Ok.. I just reviewed some plugins on the Gstreamer-rs side and I do not see problems using bindgen. I agree it offers us the most recent raw bindings.. wondering if we can even build from Csound src, and do static linking as a way for removing that trick in the build script for finding the library..

**Comment by ales-tsurko** [comment]
Regarding Csound itself, I'd keep it as is. It's easy to install using package managers, while for building we should think about dependencies of Csound and platform-dependent things. So anyway we should provide instructions for the Csound dependencies, which should be installed first. Also, static linking would require switching to LGPL license.

I'll provide a PR for bindgen-generated bindings then. I'll look into it after the weekend.
